### ISSUE TITLE
Call to a member function getTitle() on null

### ISSUE THREAD

**Issue by IL-Michi** [extcode/cart_products#104]
hello, I have the problem as I put a  bevariante2.
an error is output on the page.
I have set everything in the backend just as in Bevariante1 as soon as I delete the variante1 is displayed variant2.
Only if both are active comes this error.

**Comment by extcode** [comment]
I don't know if I got it right. It is difficult to understand without an example.
I suspect that you forgot to select either the backend variant 1 or the backend variant 2.
You currently have to create an IRRE element for each combination of backend variant 1 and backend variant 2. Assuming you have T-shirts and the color (red, green, yellow) and size (small, medium, large) configured as backend variants respectively, then you need to create an entry for each combination that is available. So

red - small
red - medium
red - large
green - medium
yellow - medium
yellow - large

Then green in small and large and yellow in small would not exist.
The reason is the price and stock management for each combination.

I am aware that this is currently not so easy for editors to maintain, especially if there are many combinations. If it should be another, then I need a more detailed description.

**Comment by IL-Michi** [comment]
ok i see.
wouldn't it be possible to choose this in the front end in another dropdown menu ?
So it is already mega complicated for the customer

**Comment by extcode** [comment]
There is a JavaScript File in the Resources/JavaScript folder. Documentated in the Changelog https://github.com/extcode/cart_products/blob/main/Documentation/Changelog/2.4/Feature-71-AllowToRenderBackendVariantsInDifferendSelectors.rst.

**Comment by IL-Michi** [comment]
MEGA Perfect Work thanks for this extension.
