### ISSUE TITLE
Make extension compatible to TYPO3 v12.4

### ISSUE THREAD

**Issue by extcode** [extcode/cart_products#123]

**Comment by rintisch** [comment]
If you want to use a v12 compatible version you can use https://github.com/rintisch/cart_products/tree/develop

Together with [github.com/rintisch/cart/blob/develop/](https://github.com/rintisch/cart/blob/develop/) you can use cart and cart_products in TYPO3 v12. This is thought as temporary solution for people who want to prepare updates until the official extensions follow.
I created those branches for my own project but thought it might help others as well. It's also a good change to find further bugs that needs to be fixed.
Be aware that I made some commit which contain changes which are not confirmed by the owner (e.g. https://github.com/extcode/cart/pull/482 or https://github.com/extcode/cart/pull/481 )To use both of my versions with composer you need to add the following lines to your composer:

```json
"repositories": [
        {
			"type": "vcs",
			"url": "git@github.com:rintisch/cart.git",
			"no-api": true
		},
        {
			"type": "vcs",
			"url": "git@github.com:rintisch/cart_products.git",
			"no-api": true
		},
]
```

and

```json
"require": {
   "extcode/cart": "dev-develop",
   "extcode/cart_products": "dev-develop",
}
```
It might be a good idea to use hashed to get specific states of the branches because you might want to have full control. You can find the hashes on https://github.com/rintisch/cart/commits/develop/ and https://github.com/rintisch/cart_products/commits/develop/
(I have not tested whether this actually works :see_no_evil:)

```json
"require": {
   "extcode/cart": "dev-develop#d80c93a0f3f6acdc6db45a7a5d8837326cba9213",
   "extcode/cart_products": "dev-develop#a17cc727fd446569dd20acc17e83298d53d9c486",
}
```

The latest documentation can be found within the repos which is quite uncomfortable to read but I have no solution for this. For EXT:cart you can find a quite updated version online (https://docs.typo3.org/p/extcode/cart/main/en-us/Index.html) but for EXT:cart_products you have to dig into the repos...

**Comment by sitsCHO** [comment]
Are there any news about a TYPO3 12.4 compatible version of the official cart_products extension? (cart has its official version for T3 12.4). And is it possible to use the official cart 9 with the fork of cart_products from @rintisch ?

**Comment by rintisch** [comment]
I would not use it in production. But you can use it for the upgrade. As far as I know wants @extcode make a stable release this week.

**Comment by sadlands** [comment]
Hello @extcode , are there any news regarding the official TYPO3 12.4 compatible version? Thank you!

**Comment by extcode** [comment]
I am pleased to be able to close this ticket with the release of version 5.0.0. The next version is in preparation.
