### ISSUE TITLE
When Using AJAX Mini cart doesn't update

### ISSUE THREAD

**Issue by HenryAveMedi** [extcode/cart_products#93]
any idea to what i have to do to access the new cart object and render it in the mini cart?

**Comment by rintisch** [comment]
@HenryAveMedi Is this still an open issue for you?

**Comment by khlifanisos** [comment]
i 'am having the same problem here any solution please ?

**Comment by rintisch** [comment]
Do you mean how to add it to the page?

Could you try the following

```typoscript
lib.miniCart = COA_INT
lib.miniCart {
  10 = USER_INT
  10 {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Cart
    pluginName = MiniCart
    vendorName = Extcode
  }
}
```

I thought I documented it but I missed that...

**Comment by rintisch** [comment]
@khlifanisos Did my comment help you? Or are you looking for something different?

**Comment by khlifanisos** [comment]
@rintisch my problem is that when i put the extension cart before my main extension (in the template>edit-the-whole-template-record>includes ) the add to cart button doesn't work anymore and when i put the it under my main extension it works fine the AddToCartbyAjax works fine and the  product is added to the mini cart in my site

**Comment by rintisch** [comment]
@khlifanisos Now I can understand your problem better. But it's not the problem which was initially mentioned in this ticket as I understand it.
Unfortunately I cannot help you with the given information because I do not know what your main extension is doing and which cart version you are using. With an older version of EXT:cart the Javascript is added via TypoScript. Maybe your main extension overwrites this JavaScript?
Have you tested whether the JavaScript from EXT:cart is still present when the main extension is placed underneath EXT:cart?

**Comment by rintisch** [comment]
I will close this issue due to missing feedback. You're welcome to reopen it!
